title: Eric Wang
#logo: /assets/img/profilephoto.png
description: University of California, San Diego<br>B.S. Computer Science and B.S. Math Economics<br><a href="https://github.com/eric184wang">GitHub</a><br><a href="https://drive.google.com/file/d/1aD1Q8Rm5xQwZfn4NFWAy9OCRt3EvrjLQ/view?usp=sharing">Resume</a>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
