title: Eric Wang
description: University of California, San Diego<br>B.S. Computer Science<br>B.S. Math Economics<br><a href="https://github.com/eric184wang">GitHub</a><br><a href="https://drive.google.com/file/d/15q7go_louvaaV1Nuqdu_1EOrbefbBo9L/view?usp=sharing">Resume</a>
logo: /assets/img/IMG_2658.png
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
